version: '3.8'
services:
  postgres:
    image: postgres:15
    container_name: mobile_app_postgres
    restart: always
    environment:
      POSTGRES_USER: mobileuser
      POSTGRES_PASSWORD: mobilepass
      POSTGRES_DB: mobileappdb
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
#     networks:
#       - mobile-net   # ðŸ‘ˆ gÃ¡n vÃ o máº¡ng riÃªng

#   nestjs:
#     # image: 528192012668.dkr.ecr.ap-southeast-1.amazonaws.com/mobile-app-backend:latest
#     image: mobile-app-backend:latest
#     env_file:
#       - .env
#     ports:
#       - "8080:8080"
#     depends_on:
#       - postgres
#     networks:
#       - mobile-net   # ðŸ‘ˆ cÃ¹ng máº¡ng vá»›i postgres

# networks:
#   mobile-net:       # ðŸ‘ˆ network kiá»ƒu bridge
#     driver: bridge
volumes:
  pgdata: